#!/bin/sh
. /lib/functions.sh
. /lib/functions/network.sh
. /lib/mwan3/mwan3.sh

main()
{
	local IP family

	config_load mwan3
	family=$1
	[ -z $family ] && family=ipv4
	if [ "$family" = ipv6 ]; then
		IP="$IP6"
	else
		IP="$IP4"
	fi
	mwan3_init

	$IP monitor route | while read line; do
		[ -z "${line##*table*}" ] && continue
		LOG debug "handling route update $family $line"
		mwan3_lock "service" "mwan3rtmon"
		mwan3_rtmon_route_handle "$line" "$family"
		mwan3_unlock "service" "mwan3rtmon"
	done
}
main "$@"
